import subprocess
import sys

visualCflags, visualCflagse = subprocess.Popen(["pkg-config", "--cflags", "libvisual-0.5"],
    stderr=subprocess.PIPE, stdout=subprocess.PIPE).communicate()

glibCflags, _ = subprocess.Popen(Split("pkg-config --cflags glib-2.0"),
        stderr=subprocess.PIPE, stdout=subprocess.PIPE).communicate()

output = visualCflags + " " + glibCflags + " -I ../../../libcalc/ -I ../../../common/ -I ../../../ -I ../../../src/"

env = Environment(CCFLAGS = Split("-g -Wall " + output))

visualLdflags, visualLdflagse = subprocess.Popen(["pkg-config", "--libs", "libvisual-0.5"],
    stderr=subprocess.PIPE, stdout=subprocess.PIPE).communicate()

glibLdflags, _ = subprocess.Popen(Split("pkg-config --libs glib-2.0"),
        stderr=subprocess.PIPE, stdout=subprocess.PIPE).communicate()

output = visualLdflags + " " + glibLdflags + " ../../../../visscript-evaluator/libvisscript.a"

libs = env.ParseFlags(Split(output));
env.MergeFlags(libs)

plugin = env.SharedLibrary(["actor_avs_superscope.c"]);

env.Install("/usr/lib/libvisual-0.5/actor/", plugin);
env.Alias('install', '/usr/lib/libvisual-0.5/actor')


